# Generated by Django 5.1.15 on 2026-07-22 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gimnasio', '0007_progreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='PRINCIPIANTE', max_length=15)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gimnasio.gimnasio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.CharField(default='10-12', help_text='Ej: "10-12", "15", "hasta el fallo"', max_length=30)),
                ('descanso_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, default='')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='rutinas.rutina')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
