# Generated by Django 5.1.15 on 2026-06-18 02:39

from django.db import migrations


def assign_gimnasio_to_clients(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Gimnasio = apps.get_model('gimnasio', 'Gimnasio')
    Cliente = apps.get_model('gimnasio', 'Cliente')

    # Obtener todos los ADMIN
    admins = User.objects.filter(role='ADMIN')

    if admins.exists():
        # Crear un Gimnasio para cada ADMIN que no tenga uno
        for admin in admins:
            if not hasattr(admin, 'gimnasio_admin') or admin.gimnasio_admin is None:
                Gimnasio.objects.create(nombre=f'Gimnasio de {admin.email}', owner=admin)

        # Usar el gimnasio del primer ADMIN para clientes huérfanos
        primer_admin = admins.first()
        gimnasio_default = primer_admin.gimnasio_admin
    else:
        # No hay ADMINs: crear gimnasio por defecto
        gimnasio_default = Gimnasio.objects.create(nombre='Gimnasio Principal')

    # Asignar clientes huérfanos al gimnasio por defecto
    clientes_huerfanos = Cliente.objects.filter(gimnasio__isnull=True)
    clientes_huerfanos.update(gimnasio=gimnasio_default)

    # Asignar ENTRENADORES al gimnasio del primer ADMIN (si existe)
    if admins.exists():
        entrenadores = User.objects.filter(role='ENTRENADOR', gimnasio__isnull=True)
        entrenadores.update(gimnasio=gimnasio_default)


def reverse_assign_gimnasio_to_clients(apps, schema_editor):
    # No se puede revertir fácilmente, pero se puede limpiar
    Gimnasio = apps.get_model('gimnasio', 'Gimnasio')
    Gimnasio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_gimnasio_cliente_gimnasio'),
        ('accounts', '0002_user_gimnasio'),
    ]

    operations = [
        migrations.RunPython(assign_gimnasio_to_clients, reverse_assign_gimnasio_to_clients),
    ]