# Generated by Django 5.1.15 on 2026-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0004_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, default='', help_text='Número de comprobante/referencia de la transacción', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta (Legacy)'), ('NEQUI_DAVIPLATA', 'Nequi / Daviplata'), ('BREB', 'BRE-B')], max_length=20),
        ),
    ]
