# Generated by Django 5.1.15 on 2026-06-22 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0005_pago_referencia_alter_pago_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('cupo_maximo', models.PositiveIntegerField(default=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entrenador', models.ForeignKey(limit_choices_to={'role': 'ENTRENADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to=settings.AUTH_USER_MODEL)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gimnasio.gimnasio')),
            ],
            options={
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=12)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gimnasio.clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reserva'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'CONFIRMADA')), fields=('cliente', 'clase'), name='unique_reserva_activa_por_clase')],
            },
        ),
    ]
