# Generated by Django 5.1.15 on 2026-07-22 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0006_cliente_user_clase_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='progreso/')),
                ('nota', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='gimnasio.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
