# Generated by Django 5.1.15 on 2026-07-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0007_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='feed_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('meta', models.PositiveIntegerField(help_text='Meta numérica a alcanzar (ej: 20 sentadillas diarias)')),
                ('unidad', models.CharField(blank=True, default='', help_text='Ej: repeticiones, días, km', max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='gimnasio.gimnasio')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogroObtenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRIMERA_RESERVA', 'Primera clase reservada'), ('ASISTENCIA_5', '5 clases reservadas'), ('ASISTENCIA_10', '10 clases reservadas'), ('ASISTENCIA_25', '25 clases reservadas'), ('PRIMER_PROGRESO', 'Primer registro de progreso'), ('PROGRESO_CONSTANCIA_5', '5 registros de progreso'), ('RETO_COMPLETADO', 'Reto completado')], max_length=25)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='gimnasio.cliente')),
                ('reto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros', to='gimnasio.reto')),
            ],
            options={
                'ordering': ['-fecha_obtenido'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_actual', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_retos', to='gimnasio.cliente')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='gimnasio.reto')),
            ],
            options={
                'ordering': ['-fecha_union'],
                'constraints': [models.UniqueConstraint(fields=('reto', 'cliente'), name='unique_participacion_por_cliente')],
            },
        ),
    ]
