# Generated by Django 5.1.15 on 2026-08-31 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0008_gimnasio_feed_habilitado_reto_logroobtenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('dias', models.PositiveIntegerField(help_text='Duración del plan en días (ej: 30, 60, 90, 365)')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_membresia', to='gimnasio.gimnasio')),
            ],
            options={
                'ordering': ['dias'],
                'constraints': [models.UniqueConstraint(fields=('gimnasio', 'dias'), name='unique_plan_dias_por_gimnasio')],
            },
        ),
    ]
