# Generated by Django 5.1.15 on 2026-09-01 00:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0011_seed_plan_anual_faltante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
