# Generated by Django 5.1.15 on 2026-06-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gimnasio', '0002_gimnasio_cliente_gimnasio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenadores', to='gimnasio.gimnasio'),
        ),
    ]
